database: mnt/c/options_data/options_data.db
output_folder: /home/chris/options_1/data
stocks:
  - AAPL
  - MSFT
  - GOOGL
  - SPY
  - TSLA
  - AMZN
  - FB
  - NFLX
  - NVDA
  - AMD
  - INTC
  - QQQ
  - BABA
  - BIDU
  - MU