# config.yaml

data:
  db_path: "data/options_data.db"
  results_csv: "data/backtest_results.csv"

backtest:
  reference_date: "2025-03-05"
  max_contracts_per_ticker: 100
  tickers:
   #W- AAPL
   #W- MSFT
   #W- GOOGL
   #W- SPY
   #W- TSLA
   #W- AMZN
   #W- FB
   #W- NFLX
   #W- NVDA
   #W- AMD
   #W- INTC
   #W- QQQ
   #W- BABA
   #W- BIDU
   - MU